version: '3.9'

services:
  webapiportfolio:
    build:
      context: .
      dockerfile: MyPortfolio.WebApi/Dockerfile
    container_name: webapiportfolio
    restart: always
    volumes:
      - /root/MyPortfolio/DB:/app/DB
      - /root/MyPortfolio/Files:/app/Files
    ports:
      - "5034:5035"
    networks:
      - network_for_portfolio

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - network_for_portfolio

networks:
  network_for_portfolio:
    driver: bridge