version: '3.9'

services:
  webapiportfolio:
    build:
      context: ..
      dockerfile: Web/MyPortfolio.WebApiDockerfile/Dockerfile
    container_name: webapiportfolio
    restart: always
    volumes:
      - /root/DB:/app/DB
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__SQLiteConnection=Data Source=/app/DB/JoboHubBot.db
      - JWTConfiguration__ValidAudience=MyPortfolio
      - JWTConfiguration__ValidIssuer=localhost
      - JWTConfiguration__Secret=MyPortfolioSecretKeyorWord
    networks:
      - network_for_portfolio

  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - network_for_portfolio


networks:
  network_for_portfolio:
    driver: bridge
