version: '3.9'

services:
  webapiportfolio:
    build:
      context: .
      dockerfile: MyPortfolio.WebApi/Dockerfile
    container_name: webapiportfolio
    restart: always
    volumes:
      - /root/Sarvar/DB:/app/DB
      - /root/Sarvar/Files:/app/Files
    environment:
      - ASPNETCORE_URLS=http://+:5034
      - ConnectionStrings__SQLiteConnection=Data Source=/app/DB/Portfolio.db
      - JWTConfiguration__ValidAudience=MyPortfolio
      - JWTConfiguration__ValidIssuer=localhost
      - JWTConfiguration__Secret=MyPortfolioSecretKeyorSecretWordForJwtSecurity
    ports:
      - "5034:5034"
    networks:
      - network_for_portfolio

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "4443:4443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - network_for_portfolio

networks:
  network_for_portfolio:
    driver: bridge